import { Todo, Category, ChatMessage } from './types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Work', color: '#3b82f6' },
  { id: '2', name: 'Personal', color: '#8b5cf6' },
  { id: '3', name: 'Shopping', color: '#ec4899' },
  { id: '4', name: 'Health', color: '#10b981' },
  { id: '5', name: 'Finance', color: '#f97316' },
  { id: '6', name: 'Other', color: '#6b7280' },
];

export const mockTodos: Todo[] = [
  {
    id: '1',
    title: 'Complete project proposal',
    description: 'Write and submit the Q1 project proposal document with all required sections.',
    completed: false,
    status: 'pending',
    priority: 'high',
    category: 'Work',
    dueDate: new Date('2026-01-25'),
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
    order: 0,
  },
  {
    id: '2',
    title: 'Review pull requests',
    description: 'Review and provide feedback on pending team PRs.',
    completed: false,
    status: 'pending',
    priority: 'medium',
    category: 'Work',
    dueDate: new Date('2026-01-22'),
    createdAt: new Date('2026-01-19'),
    updatedAt: new Date('2026-01-19'),
    order: 1,
  },
  {
    id: '3',
    title: 'Buy groceries',
    description: 'Milk, eggs, bread, fruits, and vegetables.',
    completed: false,
    status: 'pending',
    priority: 'low',
    category: 'Shopping',
    dueDate: new Date('2026-01-21'),
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
    order: 2,
  },
  {
    id: '4',
    title: 'Gym workout',
    description: 'Complete the full body workout routine.',
    completed: true,
    status: 'done',
    priority: 'medium',
    category: 'Health',
    dueDate: new Date('2026-01-20'),
    createdAt: new Date('2026-01-19'),
    updatedAt: new Date('2026-01-20'),
    order: 3,
  },
  {
    id: '5',
    title: 'Pay electricity bill',
    description: 'Pay the monthly electricity bill before the due date.',
    completed: false,
    status: 'pending',
    priority: 'high',
    category: 'Finance',
    dueDate: new Date('2026-01-24'),
    createdAt: new Date('2026-01-18'),
    updatedAt: new Date('2026-01-18'),
    order: 4,
  },
  {
    id: '6',
    title: 'Read 30 pages of book',
    description: 'Continue reading "The Pragmatic Programmer".',
    completed: false,
    status: 'pending',
    priority: 'low',
    category: 'Personal',
    dueDate: new Date('2026-01-23'),
    createdAt: new Date('2026-01-17'),
    updatedAt: new Date('2026-01-17'),
    order: 5,
  },
  {
    id: '7',
    title: 'Schedule dentist appointment',
    description: 'Call and schedule the semi-annual checkup.',
    completed: false,
    status: 'pending',
    priority: 'medium',
    category: 'Health',
    dueDate: new Date('2026-01-28'),
    createdAt: new Date('2026-01-16'),
    updatedAt: new Date('2026-01-16'),
    order: 6,
  },
  {
    id: '8',
    title: 'Update portfolio website',
    description: 'Add recent projects and update the about section.',
    completed: false,
    status: 'pending',
    priority: 'low',
    category: 'Work',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
    order: 7,
  },
  {
    id: '9',
    title: 'Team standup meeting',
    description: 'Daily standup at 10 AM with the development team.',
    completed: true,
    status: 'done',
    priority: 'high',
    category: 'Work',
    dueDate: new Date('2026-01-21'),
    createdAt: new Date('2026-01-21'),
    updatedAt: new Date('2026-01-21'),
    order: 8,
  },
  {
    id: '10',
    title: 'Plan weekend trip',
    description: 'Research destinations and book accommodation.',
    completed: false,
    status: 'pending',
    priority: 'low',
    category: 'Personal',
    dueDate: new Date('2026-01-26'),
    createdAt: new Date('2026-01-14'),
    updatedAt: new Date('2026-01-14'),
    order: 9,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    role: 'assistant',
    content: 'Hello! I\'m your AI assistant. How can I help you with your tasks today?',
    timestamp: new Date('2026-01-21T10:00:00'),
  },
];
